#!/usr/bin/env ruby
# coding: utf-8
require 'rubygems'
require 'tools'

puts ToolsUtil.get_date

ToolsDisplay.show "teste"
ToolsDisplay.show "TEXT SAMELINE sem cor ", :sameline
ToolsDisplay.show "TEXT GREEN", :green
ToolsDisplay.show "TEXT YELLOW", :yellow

msg       = "teste do encrypt".light_blue
passwd    = 'tools999'
encrypted = msg.encrypt passwd
puts (encrypted.decrypt passwd)

ToolsLog.info  "teste"
ToolsLog.warn  "teste"
ToolsLog.error "teste"
ToolsLog.debug "teste"

ToolsLog.info  "teste", :light_blue

ip = `ifconfig | grep -F 10. | awk '{print $2}' | cut -d: -f2`
ip = ip.split("\n").first if ip.include? "\n"
ap IPAddress.valid?(ip)
 
ret = ToolsNet.resolv_ip_name '8.8.8.8'
ap ret
dns = ToolsNet.resolv_dns 'www.globo.com'
ap dns


